# Generated by Django 4.2.6 on 2023-10-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_rename_credentials_credential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
