# Generated by Django 4.2.6 on 2023-10-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0003_delete_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
                ('blood', models.CharField(max_length=5)),
                ('degree', models.CharField(max_length=20)),
            ],
        ),
    ]
