# Generated by Django 4.2.4 on 2023-10-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
