# Generated by Django 4.2.4 on 2023-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_credential_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='blood',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='code',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='image',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='name',
        ),
        migrations.AddField(
            model_name='credential',
            name='imag',
            field=models.CharField(null=True),
        ),
    ]
