# Generated by Django 4.2.4 on 2023-10-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_remove_credential_blood_remove_credential_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
